base_global_planner: global_planner/GlobalPlanner
base_local_planner: dwa_local_planner/DWAPlannerROS
planner_frequency: 3.0
controller_frequency: 10.0
planner_patience: 5.0
controller_patience: 15.0
oscillation_timeout: 10.0
oscillation_distance: 0.2
shutdown_costmaps: false

GlobalPlanner:
  use_dijkstra: false
  use_quadratic: true
  allow_unknown: true
  default_tolerance: 0.2
  old_navfn_behavior: false

DWAPlannerROS:
  max_vel_x: 0.22
  min_vel_x: 0.0
  max_vel_trans: 0.22
  min_vel_trans: 0.05
  max_vel_theta: 2.75
  min_vel_theta: 0.1
  acc_lim_x: 2.5
  acc_lim_theta: 3.2
  xy_goal_tolerance: 0.20
  yaw_goal_tolerance: 0.17
  latch_xy_goal_tolerance: false
  sim_time: 1.5
  vx_samples: 8
  vtheta_samples: 20
  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  occdist_scale: 0.02
